{{-- resources/views/patients/show.blade.php --}}
@extends('layouts.admission')

@section('content')
<div class="container-fluid">
    {{-- Header --}}
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <h3 class="fw-bold text-primary mb-1">
                <i class="fas fa-user-circle me-2"></i>Patient Profile
            </h3>
            <p class="text-muted mb-0">
                <strong>{{ $patient->patient_first_name }} {{ $patient->patient_last_name }}</strong>
                <span class="badge bg-light text-dark ms-2">PID-{{ str_pad($patient->patient_id, 4, '0', STR_PAD_LEFT) }}</span>
                @if($patient->status === 'active')
                    <span class="badge bg-success ms-2">Active</span>
                @elseif($patient->status === 'discharged')
                    <span class="badge bg-secondary ms-2">Discharged</span>
                @endif
            </p>
        </div>
        <a href="{{ route('admission.patients.index') }}" class="btn btn-outline-secondary">
            <i class="fas fa-arrow-left me-1"></i> Back to Patients
        </a>
    </div>

    {{-- Flash autogenerated credentials (only right after creation) --}}
    @if(session('generatedEmail') && session('plainPassword'))
        <div class="alert alert-success shadow-sm border-0 mb-4">
            <div class="d-flex">
                <div class="me-3">
                    <i class="fas fa-key fa-2x text-success"></i>
                </div>
                <div>
                    <h5 class="alert-heading mb-1">Patient Account Created Successfully!</h5>
                    <p class="mb-1">An account has been created for this patient with the following credentials:</p>
                    <p class="mb-0">
                        <strong>Email:</strong> <code>{{ session('generatedEmail') }}</code><br>
                        <strong>Password:</strong> <code>{{ session('plainPassword') }}</code>
                    </p>
                </div>
            </div>
        </div>
    @endif

    <div class="row">
        {{-- Left Column --}}
        <div class="col-lg-12">
            {{-- Personal Information --}}
            <div class="card shadow-sm border-0 rounded-3 mb-4">
                <div class="card-header bg-white border-bottom">
                    <h5 class="mb-0">
                        <i class="fas fa-id-card me-2 text-primary"></i>Personal Information
                    </h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label class="text-muted small mb-1">Full Name</label>
                            <div class="fw-semibold">{{ $patient->patient_first_name }} {{ $patient->patient_last_name }}</div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="text-muted small mb-1">Email Address</label>
                            <div class="fw-semibold">{{ $patient->email ?? '—' }}</div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="text-muted small mb-1">Phone Number</label>
                            <div class="fw-semibold">{{ $patient->phone_number ?? '—' }}</div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="text-muted small mb-1">Date of Birth</label>
                            <div class="fw-semibold">{{ $patient->patient_birthday?->format('F d, Y') ?? '—' }}</div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="text-muted small mb-1">Gender</label>
                            <div class="fw-semibold">{{ $patient->sex ?? '—' }}</div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="text-muted small mb-1">Civil Status</label>
                            <div class="fw-semibold">{{ $patient->civil_status ?? '—' }}</div>
                        </div>
                        <div class="col-md-12 mb-0">
                            <label class="text-muted small mb-1">Address</label>
                            <div class="fw-semibold">{{ $patient->address ?? '—' }}</div>
                        </div>
                    </div>
                </div>
            </div>
            
            {{-- Medical Details --}}
            <div class="card shadow-sm border-0 rounded-3 mb-4">
                <div class="card-header bg-white border-bottom">
                    <h5 class="mb-0">
                        <i class="fas fa-notes-medical me-2 text-danger"></i>Medical Information
                    </h5>
                </div>
                <div class="card-body">
                    <div class="row mb-3">
                        <div class="col-md-12">
                            <label class="text-muted small mb-1">Primary Reason for Visit</label>
                            <div class="fw-semibold">{{ $patient->medicalDetail?->primary_reason ?? '—' }}</div>
                        </div>
                    </div>
                    
                    <div class="row mb-4">
                        <div class="col-md-12">
                            <label class="text-muted small mb-1">Vital Signs</label>
                            <div class="d-flex flex-wrap gap-3 mt-1">
                                @if($patient->medicalDetail?->weight)
                                    <div class="badge bg-light text-dark p-2">
                                        <i class="fas fa-weight me-1 text-primary"></i>
                                        Weight: {{ $patient->medicalDetail->weight }} kg
                                    </div>
                                @endif
                                
                                @if($patient->medicalDetail?->height)
                                    <div class="badge bg-light text-dark p-2">
                                        <i class="fas fa-ruler-vertical me-1 text-primary"></i>
                                        Height: {{ $patient->medicalDetail->height }} cm
                                    </div>
                                @endif
                                
                                @if($patient->medicalDetail?->temperature)
                                    <div class="badge bg-light text-dark p-2">
                                        <i class="fas fa-thermometer-half me-1 text-danger"></i>
                                        Temp: {{ $patient->medicalDetail->temperature }}°F
                                    </div>
                                @endif
                                
                                @if($patient->medicalDetail?->blood_pressure)
                                    <div class="badge bg-light text-dark p-2">
                                        <i class="fas fa-heart me-1 text-danger"></i>
                                        BP: {{ $patient->medicalDetail->blood_pressure }}
                                    </div>
                                @endif
                                
                                @if($patient->medicalDetail?->heart_rate)
                                    <div class="badge bg-light text-dark p-2">
                                        <i class="fas fa-heartbeat me-1 text-danger"></i>
                                        HR: {{ $patient->medicalDetail->heart_rate }} bpm
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>

                    @php
                        $history = $patient->medicalDetail?->medical_history;
                        if (is_string($history)) {
                            $history = json_decode($history, true) ?: [];
                        } elseif (! is_array($history)) {
                            $history = [];
                        }

                        $allergies = $patient->medicalDetail?->allergies;
                        if (is_string($allergies)) {
                            $allergies = json_decode($allergies, true) ?: [];
                        } elseif (! is_array($allergies)) {
                            $allergies = [];
                        }
                    @endphp

                    <div class="row mb-4">
                        <div class="col-md-12">
                            <label class="text-muted small mb-2">Medical History</label>
                            @if(empty($history) || (collect($history)->filter(fn($v,$k)=>$k!=='others' && $v)->isEmpty() && empty($history['others'])))
                                <p class="text-muted mb-0">No medical history recorded</p>
                            @else
                                <div class="d-flex flex-wrap gap-2">
                                    @foreach($history as $key => $value)
                                        @continue($key === 'others' || !$value)
                                        <span class="badge bg-info text-dark p-2">
                                            <i class="fas fa-check-circle me-1"></i>
                                            {{ ucwords(str_replace('_',' ',$key)) }}
                                        </span>
                                    @endforeach
                                </div>
                                @if(!empty($history['others']))
                                    <div class="mt-2">
                                        <span class="text-muted">Other conditions:</span>
                                        <span>{{ $history['others'] }}</span>
                                    </div>
                                @endif
                            @endif
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <label class="text-muted small mb-2">Allergies</label>
                            @if(empty($allergies) || (collect($allergies)->filter(fn($v,$k)=>$k!=='others' && $v)->isEmpty() && empty($allergies['others'])))
                                <p class="text-muted mb-0">No allergies recorded</p>
                            @else
                                <div class="d-flex flex-wrap gap-2">
                                    @foreach($allergies as $key => $value)
                                        @continue($key === 'others' || !$value)
                                        <span class="badge bg-danger bg-opacity-75 text-white p-2">
                                            <i class="fas fa-allergies me-1"></i>
                                            {{ $key==='none'
                                              ? 'No Known Allergies'
                                              : ucwords(str_replace('_',' ',$key))
                                            }}
                                        </span>
                                    @endforeach
                                </div>
                                @if(!empty($allergies['others']))
                                    <div class="mt-2">
                                        <span class="text-muted">Other allergies:</span>
                                        <span>{{ $allergies['others'] }}</span>
                                    </div>
                                @endif
                            @endif
                        </div>
                    </div>
                </div>
            </div>

            {{-- Admission Details --}}
            <div class="card shadow-sm border-0 rounded-3">
                <div class="card-header bg-white border-bottom d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">
                        <i class="fas fa-hospital me-2 text-success"></i>Admission Information
                    </h5>
                    @if($patient->admissionDetail && $patient->status !== 'finished')
                        <div>
                            <button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#changeDoctorModal">
                                <i class="fas fa-user-md me-1"></i> Change Doctor
                            </button>
                            {{-- Entry --}}
                            <a href="{{ route('admission.patients.change-room-bed.form', $patient->patient_id) }}" class="btn btn-sm btn-outline-secondary ms-2">
                                <i class="fas fa-bed me-1"></i> Change Room/Bed
                            </a>
                        </div>
                    @endif
                </div>
                <div class="card-body">
                    @if(!$patient->admissionDetail)
                        <div class="text-center py-4">
                            <div class="text-muted mb-3">
                                <i class="fas fa-hospital-alt fa-3x"></i>
                            </div>
                            <h6 class="mb-0">No admission records found</h6>
                        </div>
                    @else
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small mb-1">Admission Date</label>
                                <div class="fw-semibold">{{ $patient->admissionDetail->admission_date->format('F d, Y - g:i A') }}</div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small mb-1">Department</label>
                                <div class="fw-semibold">{{ $patient->admissionDetail->department?->department_name ?? '—' }}</div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small mb-1">Attending Doctor</label>
                                <div class="d-flex align-items-center">
                                    <div class="bg-success bg-opacity-10 rounded-circle d-flex align-items-center justify-content-center me-2" style="width: 32px; height: 32px;">
                                        <i class="fas fa-user-md text-success"></i>
                                    </div>
                                    <div class="fw-semibold">
                                        {{ $patient->admissionDetail->doctor?->doctor_name ?? '—' }}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small mb-1">Room/Bed Assignment</label>
                                <div class="d-flex align-items-center">
                                    <div class="bg-info bg-opacity-10 rounded-circle d-flex align-items-center justify-content-center me-2" style="width: 32px; height: 32px;">
                                        <i class="fas fa-bed text-info"></i>
                                    </div>
                                    <div class="fw-semibold">
                                        @if($patient->admissionDetail->room_number && $patient->admissionDetail->bed_number)
                                            Room {{ $patient->admissionDetail->room_number }} / Bed {{ $patient->admissionDetail->bed_number }}
                                        @else
                                            —
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <label class="text-muted small mb-1">Admission Notes</label>
                                <div class="fw-semibold">{{ $patient->admissionDetail->admission_notes ?? '—' }}</div>
                            </div>
                        </div>
                    @endif
                </div>
            </div>
        </div>
        
        {{-- Right Column --}}
        {{-- <div class="col-lg-4">
            {{-- Status Card 
            <div class="card shadow-sm border-0 rounded-3 mb-4">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <h6 class="text-muted mb-0">Status</h6>
                        @if($patient->status === 'active')
                            <span class="badge bg-success">Active</span>
                        @elseif($patient->status === 'discharged')
                            <span class="badge bg-secondary">Discharged</span>
                        @else
                            <span class="badge bg-warning text-dark">{{ ucfirst($patient->status ?? 'Unknown') }}</span>
                        @endif
                    </div>
                    @if($patient->status === 'active' && $patient->admissionDetail)
                        <div class="mt-3 pt-3 border-top">
                            <div class="text-center">
                                <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#dischargeModal">
                                    <i class="fas fa-sign-out-alt me-1"></i> Discharge Patient
                                </button>
                            </div>
                        </div>
                    @endif
                </div>
            </div> --}}
            
            {{-- Billing Information --}}
            <div class="card shadow-sm border-0 rounded-3 mb-4">
                <div class="card-header bg-light">
                    <h6 class="mb-0">
                        <i class="fas fa-file-invoice-dollar me-2"></i>Billing Information
                    </h6>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <strong>Guarantor Name:</strong><br>
                        <span class="text-muted">{{ $patient->billingInformation?->guarantor_name ?? '—' }}</span>
                    </div>
                    <div class="mb-0">
                        <strong>Guarantor Relationship:</strong><br>
                        <span class="text-muted">{{ $patient->billingInformation?->guarantor_relationship ?? '—' }}</span>
                    </div>
                    
                    <hr>
                    
                    {{-- <div class="mt-3">
                        <a href="{{ route('patient.billing', $patient->patient_id) }}" class="btn btn-outline-primary btn-sm w-100">
                            <i class="fas fa-eye me-1"></i> View Billing Details
                        </a>
                    </div> --}}
                </div>
            </div>

            {{-- Emergency Contact --}}
            </div>
        </div>
    </div>
</div>

{{-- Change Doctor Modal --}}
@if($patient->admissionDetail && $patient->status !== 'discharged')
<div class="modal fade" id="changeDoctorModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <form class="modal-content" action="{{ route('admission.patients.change-doctor', $patient->patient_id) }}" method="POST">
            @csrf
            @method('PATCH')
            <div class="modal-header">
                <h5 class="modal-title">Change Doctor</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label class="form-label">Current Doctor</label>
                    <input type="text" class="form-control" value="{{ $patient->admissionDetail->doctor->doctor_name ?? 'No doctor assigned' }}" readonly>
                </div>
                
                <div class="mb-3">
                    <label class="form-label">New Doctor</label>
                    <select name="doctor_id" class="form-select" required>
                        <option value="">Select new doctor...</option>
                        @php
                            // Show all available doctors regardless of department
                            $availableDoctors = \App\Models\Doctor::all();
                        @endphp
                        @foreach($availableDoctors as $doctor)
                            <option value="{{ $doctor->doctor_id }}">
                                {{ $doctor->doctor_name }} 
                                @if($doctor->department)
                                    ({{ $doctor->department->department_name }})
                                @endif
                            </option>
                        @endforeach
                    </select>
                    <div class="form-text">All doctors are shown regardless of department.</div>
                </div>

                {{-- <div class="mb-3">
                    <label class="form-label">Reason for Change</label>
                    <textarea name="change_reason" class="form-control" rows="3" placeholder="Optional: Reason for changing doctor..."></textarea>
                </div> --}}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-user-md me-1"></i> Change Doctor
                </button>
            </div>
        </form>
    </div>
</div>
@endif

@endsection

@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    // SweetAlert for success/error messages
    @if(session('success'))
        Swal.fire({
            icon: 'success',
            title: 'Success!',
            html: '{!! session('success') !!}',
            timer: 3000,
            showConfirmButton: false
        });
    @endif

    @if(session('error'))
        Swal.fire({
            icon: 'error',
            title: 'Error!',
            text: '{{ session('error') }}'
        });
    @endif

    // Wait for modal to be fully shown before attaching event listeners
    document.addEventListener('DOMContentLoaded', function() {
        const modal = document.getElementById('changeRoomBedModal');
        
        if (modal) {
            modal.addEventListener('shown.bs.modal', function() {
                console.log('=== MODAL OPENED ===');
                
                const roomSelect = document.getElementById('roomSelect');
                const bedSelect = document.getElementById('bedSelect');
                const submitBtn = document.getElementById('submitBtn');

                if (!roomSelect || !bedSelect || !submitBtn) return;

                // Remove any existing event listeners
                const newRoomSelect = roomSelect.cloneNode(true);
                roomSelect.parentNode.replaceChild(newRoomSelect, roomSelect);

                document.getElementById('roomSelect').addEventListener('change', function() {
                    const roomId = this.value;
                    if (!roomId) {
                        bedSelect.innerHTML = '<option value="">First select a room...</option>';
                        bedSelect.disabled = true;
                        submitBtn.disabled = true;
                        return;
                    }
                    
                    // IMPORTANT: Try with both URL formats
                    const url = `/admission/rooms/${roomId}/beds`;
                    console.log('Fetching from:', url);
                    
                    bedSelect.innerHTML = '<option value="">Loading beds...</option>';
                    bedSelect.disabled = true;
                    
                    // Make API request with error handling
                    fetch(url)
                        .then(response => {
                            if (!response.ok) {
                                throw new Error(`HTTP error! status: ${response.status}`);
                            }
                            return response.json();
                        })
                        .then(data => {
                            console.log('Data received:', data);
                            
                            // Manually populate beds instead of using forEach
                            bedSelect.innerHTML = '<option value="">Select a bed...</option>';
                            
                            if (data && data.length > 0) {
                                for (let i = 0; i < data.length; i++) {
                                    const bed = data[i];
                                    const option = new Option(
                                        `Bed ${bed.bed_number}` + (bed.rate ? ` - ₱${parseFloat(bed.rate).toLocaleString('en-PH', {minimumFractionDigits: 2})} / day` : ''),
                                        bed.bed_id
                                    );
                                    bedSelect.options.add(option);
                                }
                                bedSelect.disabled = false;
                            } else {
                                bedSelect.innerHTML = '<option value="">No available beds</option>';
                                bedSelect.disabled = true;
                            }
                        })
                        .catch(error => {
                            // Try alternative URL format if first one fails
                            const altUrl = `/rooms/${roomId}/beds`;
                            console.log('Error with first URL, trying:', altUrl);
                            
                            fetch(altUrl)
                                .then(response => response.ok ? response.json() : Promise.reject('Failed with alt URL'))
                                .then(data => {
                                    console.log('Alt URL data received:', data);
                                    
                                    bedSelect.innerHTML = '<option value="">Select a bed...</option>';
                                    
                                    if (data && data.length > 0) {
                                        for (let i = 0; i < data.length; i++) {
                                            const bed = data[i];
                                            const option = new Option(
                                                `Bed ${bed.bed_number}` + (bed.rate ? ` - ₱${parseFloat(bed.rate).toLocaleString('en-PH', {minimumFractionDigits: 2})} / day` : ''),
                                                bed.bed_id
                                            );
                                            bedSelect.options.add(option);
                                        }
                                        bedSelect.disabled = false;
                                    } else {
                                        bedSelect.innerHTML = '<option value="">No available beds</option>';
                                        bedSelect.disabled = true;
                                    }
                                })
                                .catch(finalError => {
                                    console.error('All attempts failed:', finalError);
                                    bedSelect.innerHTML = '<option value="">Error loading beds</option>';
                                    bedSelect.disabled = true;
                                });
                        });
                });

                // Enable submit button when bed is selected
                bedSelect.addEventListener('change', function() {
                    submitBtn.disabled = !this.value;
                });
            });
        }
    });
</script>

@endsection